# Generated by Django 5.1 on 2025-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_student_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='stuid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
