# Generated by Django 5.1 on 2025-08-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_remove_student_id_alter_student_stuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
